name: Tests

on:
  push:
    branches:    
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go

      - name: Run Unit tests
        run: make test
